server:
  port: 8401

spring:
  application:
    name: hyp-monitor-admin
  boot:
    admin:
      ui:
        title: ${spring.application.name}
  security:
    user:
      name: hyp
      password: 123456