server:
  port: 8001
  servlet:
    context-path: /register

spring:
  application:
    name: hyp-register
  security:
    user:
      name: hyp
      password: 123456
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: hyp
        password: 123456

eureka:
  instance:
    #指定了Eureka服务端的地址
    hostname: localhost
  client:
    #是否将服务注册到Eureka服务端，由于我们这里是单节点的Eureka服务端，所以这里指定false
    register-with-eureka: false
    #是否从Eureka服务端获取服务信息，因为这里是单节点的Eureka服务端，并不需要从别的Eureka服务端同步服务信息，所以这里设置为false
    fetch-registry: false
    #微服务更新实例信息的变化到Eureka服务端的间隔时间，单位为秒，这里指定为30秒
    instance-info-replication-interval-seconds: 30
    #Eureka服务端的地址
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS